%
%   ..generate a line of probes for 2D hirose simulations
%

x0=46;
y0=42;

x1=26;
y1=4;

npts=50;

%---------------compute line
ds=1./(npts-1);
s=0:ds:1;
dx=x1-x0;
dy=y1-y0;

x= x0 + dx*s;
y= y0 + dy*s;
jj=1:npts;

%--------------- output to probe file
out=[jj', x', y', zeros(npts,1)];

fd=fopen('probeLine.probes','w');
fprintf(fd, '#\n');
fprintf(fd, '# Probes for 2D hirose runs. \n');
fprintf(fd, '#   Generated by CellWave/generateProbeLine.m \n');
fprintf(fd, '#\n');
fprintf(fd, '%3d  %24.16f  %24.16f   %5.2f \n', out');
fclose(fd);
